### ISSUE TITLE
Automatic support for DTSTAMP

### ISSUE THREAD

**Issue by madflier** [C4ptainCrunch/ics.py#200]
Hello,

Total novice here, I'm afraid.

When creating an all day event, using a start time and then converting to all day event, I can successfully generate an ics file containing multiple such events.

However, this file doesn't validate and causes some problems eg importing natively into android calendar.

The validation issue is because there is no DTSTAMP property in the VEVENT

Looking at the source code (again, be gentle please, novice) this seems to be set when (and only when) the event.created thingy is set.

However, this is a MANDATORY entry for this type of event (all day, anniversary or basically any VEVENT).

See here:
[Linky](https://www.kanzaki.com/docs/ical/dtstamp.html) 

Example ics file without DTSTAMP

```BEGIN:VCALENDAR
PRODID:ics.py - http://git.io/lLljaA
VERSION:2.0
BEGIN:VEVENT
DTSTART;VALUE=DATE:20191002
SUMMARY:Lazy Bed Day
TRANSP:OPAQUE
UID:ad7a84a7-8d24-41c9-a4cd-26cb2da14e11@ad7a.org
END:VEVENT
BEGIN:VEVENT
DTSTART;VALUE=DATE:20191001
SUMMARY:Busy Frantic Day
TRANSP:OPAQUE
UID:be265bab-c7a7-4b09-b20e-1c7419b94d8d@be26.org
END:VEVENT
END:VCALENDAR
```

Obvs it would be nice if this mandatory entry was included by default.

Ta

**Comment by madflier** [comment]
I can confirm that setting Event().created attribute solves this problem.

**Comment by C4ptainCrunch** [comment]
Hi @madflier!
Thanks for this nice bug report :)

From what i read from the spec, it seems to me that `DTSTAMP` is not mandatory: if you look at the [definition from `VEVENT`](https://www.kanzaki.com/docs/ical/vevent.html#def) we can see the following:
```
             ; the following are optional,
             ; but MUST NOT occur more than once

             class / created / description / dtstart / geo /
             last-mod / location / organizer / priority /
             dtstamp / seq / status / summary / transp /
             uid / url / recurid /
```

Nevertheless, i understand that even if it's optional, it still bothers you.
What behaviour would you expect/like ics.py to have regarding `DTSTAMP` ?

**Comment by madflier** [comment]
Hmmm. Thank you, I see.

The definition of DTSTAMP:

```ConformanceThis property MUST be included in the "VEVENT
<https://www.kanzaki.com/docs/ical/vevent.html>", "VTODO
<https://www.kanzaki.com/docs/ical/vtodo.html>", "VJOURNAL
<https://www.kanzaki.com/docs/ical/vjournal.html>" or "VFREEBUSY
<https://www.kanzaki.com/docs/ical/vfreebusy.html>" calendar components
```
(apologies if formatting issues, I'm essentially using a potato to reply)

seems to be in conflict with that.

Let me have a dig around and update the ticket.

In terms of your second question, I can see two potential solutions -
namely use the current datetime as the DTSTAMP transparently (this is what
it is designed to signify, after all) _or_ raise a warning when creating an
all day event with no DTSTAMP specified.

If it is, in fact, optional, then I can't see any reason to alter behaviour.

As I say, I'll look further into this and update, if you're happy with that.

Stu

**Comment by madflier** [comment]
@C4ptainCrunch thank you for your reply and patience.

OK. So, to summarise, the https://www.kanzaki.com/docs/ical/ documentation seems to be _inconsistent_ here, with the VEVENT definition suggesting (inclusion of DTSTAMP) optional, the DTSTAMP definition suggesting mandatory (in VEVENT).

So, going back to the original rfc [here](https://tools.ietf.org/html/rfc5545#section-3.6.1), we see that:

```
3.6.1.  Event Component

Component Name:  VEVENT

   Purpose:  Provide a grouping of component properties that describe an event.

   Format Definition:  A "VEVENT" calendar component is defined by the following notation:

       eventc     = "BEGIN" ":" "VEVENT" CRLF
                    eventprop *alarmc
                    "END" ":" "VEVENT" CRLF

       eventprop  = *(
                  ;
                  ; The following are REQUIRED,
                  ; but MUST NOT occur more than once.
                  ;
                  dtstamp / uid /
```

so I would propose that the definition that you link to is incorrect.

This is supported by ics file validators such as found here: [https://icalendar.org/validator.html](https://icalendar.org/validator.html)

If a behaviour change is desired, I would suggest proceeding as my previous comment.

Many thanks,

Stu

**Comment by madflier** [comment]
@C4ptainCrunch 

Ah, figured it out.

The documentation that you have linked to is based on [rfc2445](https://www.ietf.org/rfc/rfc2445.txt), whereas ics.py claims compliance with [rfc5545](https://tools.ietf.org/html/rfc5545#section-3.6.1) (which is what I have linked to above).

They seem to have changed the definition of VEVENT between these two rfc's.

I rest my case ;-)

**Comment by C4ptainCrunch** [comment]
Indeed, i was looking at rfc2445 and not 5545, my bad.
We indeed have to specify it. I guess, setting it at datetime.utcnow() on the instantiation will be enough.

**Comment by madflier** [comment]
Yes, if not otherwise set.

Many thanks

**Comment by JMMarchant** [comment]
At the moment "DTSTAMP" seems to be mapped to the `created` attribute on the Event class with no attribute available for the "CREATED" iCal property. It should be noted that these are [different iCal properties](https://stackoverflow.com/questions/11594921/whats-the-difference-between-created-and-dtstamp-in-the-icalendar-format) and, whilst the output is currently correct as ics.py similarly _writes out_ DTSTAMP, it's a bit confusing and there is no way to set/interact with the "CREATED" iCal property.

**Comment by C4ptainCrunch** [comment]
I agree with you, i guess i was not aware of the `CREATED` when i chose to map `DTSTAMP` to `.created`. I think we should fix this mapping with a breaking change and document it. What "human readable" name would you suggest for `DTSTAMP` ?

**Comment by JMMarchant** [comment]
Unless it's used for something else (a quick glance through the spec doesn't seem like anything else would need to map to it) I think `timestamp` itself might work.

**Comment by healther** [comment]
before 770051c2989725b8cc40886ca9654a5c46fba81f a dumped event would complete the `DTSTAMP` field with the current time. 

I noticed the difference because the Android calendar from my girlfriend refused to accept a newly dumped ics file. However even after manually adding the created information this problem persists, so I'm not sure where that breakage comes from.. So treat it as "changed behaviour which wasn't announced" rather than an actual breakage. That being said, the output change in 770051c2989725b8cc40886ca9654a5c46fba81f looks like a drive-by.
